import path from "node:path";

const cwdName = path.basename(process.cwd()).toLowerCase();

export const CONFIG = {
  // Network.
  wsPort: Number(process.env.PORT ?? 8787),
  broadcastIntervalMs: 100,

  // The server is authoritative and advances the world 10 times per second.
  tickMs: 100,
  snapshotSaveEveryTicks: 20,
  // Феромонную сетку (самая тяжёлая часть снапшота) шлём не каждый тик, а реже.
  // Муравьи и HUD идут каждый тик; клиент переиспользует последние феромоны.
  pheromoneSendEveryTicks: 10,
  snapshotFile:
    process.env.SNAPSHOT_FILE ??
    path.resolve(process.cwd(), cwdName === "server" ? ".." : ".", "snapshot.json"),
  genomeFile:
    process.env.GENOME_FILE ??
    path.resolve(process.cwd(), cwdName === "server" ? ".." : ".", "genome.json"),
  genomeFileB:
    process.env.GENOME_FILE_B ??
    path.resolve(process.cwd(), cwdName === "server" ? ".." : ".", "genome-b.json"),
  spiderGenomeFile:
    process.env.SPIDER_GENOME_FILE ??
    path.resolve(process.cwd(), cwdName === "server" ? ".." : ".", "spider_genome.json"),

  // Surface is the only true grid in the first step.
  mapWidth: 480,
  mapHeight: 480,
  surfaceEntrance: { x: 120, y: 240 },
  surfaceEntranceB: { x: 360, y: 240 },

  // Underground still keeps the old nav nodes, plus a new diggable grid layer.
  undergroundWidth: 140,
  undergroundHeight: 98,
  undergroundEntrance: { x: 70, y: 0 },
  undergroundJunction: { x: 70, y: 35 },
  queenPos: { x: 36, y: 76 },
  storagePos: { x: 58, y: 63 },
  nurseryPos: { x: 82, y: 74 },
  eggRoomPos: { x: 48, y: 78 },
  barracksAPos: { x: 48, y: 56 },
  barracksBPos: { x: 94, y: 58 },
  tunnelWidth: 3,
  digProgressPerTick: 14,
  digProgressPerTile: 4,
  dirtPerDugTile: 1,
  dirtCarryBatch: 4,
  maxDiggers: 8,
  showUndergroundDebug: false,
  startingQueenRoomWidth: 9,
  startingQueenRoomHeight: 6,
  plannedStorageRoomWidth: 9,
  plannedStorageRoomHeight: 6,
  plannedStorageCapacity: 100,
  plannedEggRoomWidth: 8,
  plannedEggRoomHeight: 6,
  plannedEggRoomCapacity: 20,
  plannedNurseryRoomWidth: 8,
  plannedNurseryRoomHeight: 6,
  plannedNurseryCapacity: 20,
  plannedWaitingRoomWidth: 7,
  plannedWaitingRoomHeight: 5,
  plannedWaitingCapacity: 18,
  roomExpandCapacityStep: 12,
  roomExpandMaxTiles: 18,

  startingWorkers: 8,
  // A starter axe breaks the wood -> workshop -> tools bootstrap cycle.
  startingAxes: 1,
  // «Глина — это всё»: новый житель лепится из глины.
  newResidentClayCost: 3,
  startingClay: 10,
  deadClayAmount: 2.5,
  // Живой костёр: ест дрова, гаснет без них, слабый огонь замедляет жителей.
  fireWoodEveryTicks: 600,
  fireWoodCost: 1,
  fireDecay: 0.06,
  fireRecover: 0.1,
  fireLowThreshold: 0.35,
  fireLowSpeedFactor: 0.85,
  // Дождь-катастрофа.
  weatherClearMinTicks: 6000,
  weatherClearVarTicks: 3000,
  weatherWarningTicks: 600,
  weatherRainTicks: 900,
  rainWallDamageEveryTicks: 50,
  rainWallDamage: 2,
  rainWetSpeedFactor: 0.7,
  rainShelterFireRadius: 12,
  rainShelterHutRadius: 5,
  rainFireDecayMult: 3,
  wallRepairHpPerClay: 40,
  bigRainAtTicks: 15000,
  bigRainTicks: 2400,
  bigRainFireGoal: 0.5,
  // Идол — «хитрая» победа: дорогая статуя из глины и камня.
  idolCost: { clay: 25, wood: 0, stone: 5 },
  idolMaxHp: 200,
  idolBuildTicks: 500,
  maxIdolsPerColony: 1,
  startingMiners: 5,
  startingEggs: 2,
  startingLarvae: 0,
  startingFoodStorage: 100,
  maxPopulation: 30,
  campSpawnRadius: 5,
  nestCapacity: 300,

  // Worker movement and state-machine balance.
  workerSurfaceSpeed: 1.05,
  workerUndergroundSpeed: 2.2,
  entranceRadiusSurface: 1.2,
  entranceRadiusUnderground: 2.5,
  undergroundNodeRadius: 2.6,
  foodPickupRadius: 1.35,
  maxEnergy: 900,
  energyDrainPerTick: 0.24,
  lowEnergyThreshold: 250,
  workerMealCost: 0.4,
  // Hungry surface workers return before they are starving, so a failed food trip does not become a death march.
  refuelEnergyThreshold: 420,
  randomWander: 0.12,
  defenseRadius: 10,
  defenseMaxHelpers: 6,
  antAlertRange: 10,
  antSpiderSightRadius: 14,
  antFoodSightRadius: 3.5,
  superFoodSightRadius: 45,
  superFoodDirectApproachRange: 35,
  superFoodCombatRadius: 15,
  antMobCount: 6,
  antMobSpeedBonus: 0.3,
  antMobCountThreshold: 3,
  antVsAntDamage: 2.6,
  antCombatRadius: 1.4,
  warHungerThreshold: 10,
  comfortableStorage: 120,
  minForagers: 2,
  foragerFraction: 0.9,
  maxForagers: 260,
  scoutCount: 4,
  maxSearchAssistants: 260,
  spiderNearNestPenalty: 0.55,
  spiderNearNestRadius: 18,

  // Pheromones live only on surface and are represented as two Float32Array grids.
  pheromoneEvaporation: 0.982,
  pheromoneDiffusion: 0.008,
  foodPheromoneDeposit: 5,
  homePheromoneDeposit: 4,
  foodSourceScent: 2.2,
  foodSourceScentRadius: 12,
  pheromoneGradientWeight: 3.5,

  // Queen and brood lifecycle.
  eggCost: 3,
  queenMinFoodReserve: 20,
  queenMaxHp: 220,
  queenEggComfortLimit: 4,
  queenStressPerTick: 0.5,
  queenStressDamage: 0.18,
  queenRearStrength: 0.5,
  queenRearStressThreshold: 55,
  queenRearTicks: 260,
  queenStressDirtyEggTicks: 50,
  queenStressReliefPerTick: 2,
  queenHighStressDeathChance: 0.01,
  queenMaxAge: 10000,
  princessGrowthMult: 3,
  princessChance: 0.05,
  maxPrincesses: 3,
  // How often the queen tries to lay a new egg under herself.
  broodLayCooldownTicks: 95,
  // Eggs only incubate after nurses carry them to the nursery.
  eggIncubationTicks: 260,
  // Larvae grow in the nursery while a nurse is present and food is available.
  larvaGrowthNeeded: 170,
  larvaFeedPerTick: 3,
  larvaFeedFoodCost: 0.04,
  // Queen meals come from storage; missed meals increment starve, and too many missed meals kill her.
  queenEatEveryTicks: 75,
  queenFoodPerMeal: 0.65,
  queenStarveBuffer: 26,
  // Brood work only starts when the colony has enough reserve, so food gathering cannot deadlock.
  nurseMinFoodReserve: 8,
  maxConcurrentNurses: 3,
  maxNurses: 3,
  maxDirectiveNurses: 3,
  scoutFraction: 0.5,
  startingScouts: 2,
  startingNurses: 1,
  maxScouts: 5,
  foodDirectApproachRange: 3.5,
  workerSearchAssistTicks: 2200,

  // Player click on surface creates a finite food pile with this amount.
  playerFoodAmount: 80,
  carrionCount: 8,
  carrionAmount: 40,
  carrionRespawnEveryTicks: 2000,
  antCorpseFood: 1.5,
  antCorpseScentMultiplier: 0.12,
  carrionScentMultiplier: 0.25,
  carrionDecayEveryTicks: 6000,
  carrionDecayFraction: 0.04,
  foodGrowEveryTicks: 450,
  foodGrowAmount: 28,
  maxFoodSources: 28,

  // Surface spider: a wandering danger that becomes food only when the starving colony attacks it.
  spiderMaxHp: 1400,
  spiderAttackRadius: 4,
  spiderDamagePerTick: 7.0,
  antDamagePerTick: 1.3,
  spiderAvoidRadius: 7,
  spiderCarcassFood: 140,
  spiderRespawnTicks: 600,
  spiderSpeed: 0.95,
  spiderChaseSpeed: 2.2,
  spiderSprintTicks: 70,
  spiderTiredSpeed: 0.7,
  spiderRecoveryTicks: 90,
  spiderLairWebRadius: 14,
  spiderWebSpeedPenalty: 0.4,
  spiderLairEdgeMargin: 18,
  spiderLairSafeRadius: 4,
  spiderStoreSafeRadius: 5,
  spiderHungerPerTick: 0.5,
  spiderCarrionEatPerTick: 18,
  spiderFedOnKill: 420,
  spiderHungryThreshold: 900,
  spiderStarveThreshold: 1350,
  spiderStarveBuffer: 260,
  spiderDesperateFeedFactor: 0.7,
  spiderHungryAttackRadius: 5.5,
  spiderHungryDamage: 9.5,
  spiderChaseRange: 8,
  spiderEngageRange: 9,
  spiderLairMinDist: 25,
  spiderLairMaxDist: 55,
  spiderCarryAmount: 45,
  spiderHoardMax: 90,
  spiderHoardEatPerTick: 10,
  spiderMobRetreatCount: 5,
  spiderMobRetreatUtility: 2.4,
  spiderLowHpRetreatThreshold: 0.65,
  spiderLowHpRetreatUtility: 1.3,
  spiderKillWeight: 900,
  spiderSurviveWeight: 1,
  spiderLifeMaxTicks: 16000,
  spiderArchiveSize: 6,
  spiderTournamentSize: 3,
  spiderMutationRate: 0.15,
  spiderModeRepickPenalty: 0.15,
  // The colony attacks spiders only when visible surface food is essentially gone and storage is low.
  starveFoodThreshold: 3,
  starveStorageThreshold: 6,
  colonyDeathMinTicks: 120,
  colonyGraceTicks: 1200,
  generationMaxTicks: 1000000,
  fitnessPopWeight: 0,
  fitnessFoodWeight: 4,
  fitnessSpiderWeight: 2500,
  fitnessAvgPopWeight: 25,
  fitnessSurviveWeight: 0.2,
  genomeArchiveSize: 6,
  genomeTournamentSize: 3,
  genomeMutationRate: 0.15,

  // Ресурсы Clayfolk: «что видишь — то можно добыть».
  // Глиняные пятна (руками).
  clayNodeCount: 5,
  clayNodeAmount: 70,
  // Леса: рощи из отдельных деревьев (рубка топором).
  forestClusterCount: 7,
  forestClusterMinTrees: 10,
  forestClusterMaxTrees: 16,
  forestClusterRadius: 14,
  treeAmount: 6,
  maxTrees: 170,
  // Скалы: гряды валунов (кирка), не восстанавливаются.
  stoneClusterCount: 3,
  stoneClusterMinRocks: 3,
  stoneClusterMaxRocks: 5,
  stoneClusterRadius: 7,
  stoneNodeAmount: 60,
  // Ручной сбор: ветки (дерево) и россыпи камешков (камень).
  stickCount: 14,
  stickAmount: 3,
  looseStoneCount: 12,
  looseStoneAmount: 3,
  // Бутстрап у лагеря: чтобы партия всегда могла дойти до мастерской.
  campBootstrapMinRadius: 18,
  campBootstrapMaxRadius: 38,
  campBootstrapSticks: 3,
  campBootstrapLooseStones: 3,
  campBootstrapClayNodes: 1,
  // Многоударная добыча: удар раз в harvestHitTicks тиков, единица за hitsPerUnit ударов.
  harvestHitTicks: 12,
  treeHitsPerUnit: 4,
  stoneHitsPerUnit: 6,
  clayHitsPerUnit: 2,
  handHitsPerUnit: 1,
  // Рост лесов: росток -> молодое -> взрослое; взрослые сеют ростки рядом.
  treeGrowStageTicks: 3600,
  treeSeedEveryTicks: 1500,
  treeSeedChance: 0.06,
  treeSeedMinRadius: 5,
  treeSeedMaxRadius: 13,
  treeDensityRadius: 9,
  treeDensityLimit: 7,
  // Ветки/камешки/глина медленно восстанавливаются, чтобы ручной сбор не вымирал.
  resourceRespawnEveryTicks: 2500,
  resourceRespawnChance: 0.35,
  resourcePickupRadius: 1.6,
  clayReserveTarget: 40,
  woodReserveTarget: 30,
  stoneReserveTarget: 25,
  maxHarvestersPerResource: 3,
  harvestMinWorkers: 8,
  harvestMinFood: 30,

  // Постройки: хижина (точкой) и стена (кистью).
  hutCost: { clay: 8, wood: 5, stone: 0 },
  hutMaxHp: 120,
  hutPopulationBonus: 4,
  hutBuildTicks: 260,
  wallCost: { clay: 2, wood: 0, stone: 0 },
  wallMaxHp: 80,
  wallBuildTicks: 70,
  // Ворота: сегмент стены, через который проходят только свои жители.
  gateCost: { clay: 2, wood: 1, stone: 0 },
  gateMaxHp: 80,
  gateBuildTicks: 90,
  storageCost: { clay: 0, wood: 6, stone: 4 },
  storageMaxHp: 100,
  storageBuildTicks: 200,
  maxStoragesPerColony: 6,
  // Мастерская: производит инструменты из ресурсов склада.
  workshopCost: { clay: 8, wood: 4, stone: 0 },
  workshopMaxHp: 100,
  workshopBuildTicks: 220,
  maxWorkshopsPerColony: 2,
  axeCost: { wood: 2, stone: 1 },
  pickCost: { wood: 2, stone: 2 },
  rodCost: { wood: 2, stone: 0 },
  toolCraftTicks: 200,
  maxAxes: 3,
  maxPicks: 3,
  maxRods: 4,
  dropPointRadius: 3,

  // Рыбалка: постоянная популяция в каждом озере, видимый подход рыбы к поплавку и медленное восстановление.
  fishPerLake: 16,
  fishSwimSpeed: 0.035,
  fishLureSpeed: 0.11,
  fishTurnEveryTicks: 90,
  fishingStandRadius: 1.15,
  fishingBiteRadius: 0.8,
  fishingMinCastTicks: 70,
  fishRespawnMinTicks: 1100,
  fishRespawnMaxTicks: 1900,
  fishFoodYield: 5,
  maxBuildersPerSite: 2,
  maxActiveBuilders: 4,
  buildMinFood: 15,
  buildingDeliverRadius: 2.4,
  buildRadius: 2.6,
  buildingEntranceMargin: 7,
  maxHutsPerColony: 8,
  maxWallSegmentsPerColony: 160,

  // Стража: пара жителей держится у лагеря, пока жив паук.
  guardCount: 2,
  // Паника: смерть жителя пугает соседей.
  panicRadius: 8,
  panicTicks: 100,
  // Логово-экспедиция: запас паука можно разграбить, пока хозяин далеко.
  hoardLootSpiderDistance: 40,
  guardMinWorkers: 12,
  guardPatrolRadius: 11,
  guardEngageRadius: 26,

  genomeGeneBounds: {
    nurseFraction: { min: 0.1, max: 0.6 },
    digFraction: { min: 0.05, max: 0.45 },
    queenRearBias: { min: 0, max: 1 },
    forageSpread: { min: 0.1, max: 0.6 },
    spiderAttackStorage: { min: 0, max: 60 },
    layReserve: { min: 10, max: 40 },
    refuelThreshold: { min: 200, max: 600 },
    spiderAvoid: { min: 4, max: 12 },
    aggression: { min: 0, max: 1 }
  },

  spiderGeneBounds: {
    aggression: { min: 0, max: 1 },
    ambushPreference: { min: 0, max: 1 },
    chaseTriggerDist: { min: 2, max: 14 },
    swarmCaution: { min: 1, max: 8 },
    entranceAffinity: { min: 0, max: 0.6 },
    patience: { min: 50, max: 400 },
    hungerAggroGain: { min: 0, max: 1 }
  }
} as const;
